version: '3.8'

services:
  base_db:
    image: postgres:14
    environment:
      POSTGRES_USER: base_user
      POSTGRES_PASSWORD: base_password
      POSTGRES_DB: base_db
    ports:
      - "5434:5432"
    volumes:
      - base_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - base_db
    environment:
      DB_HOST: base_db
      DB_PORT: 5432
      DB_USER: base_user
      DB_PASSWORD: base_password
      DB_NAME: base_db
    ports:
      - "8080:8080"

volumes:
  base_data: