version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/db/init:/docker-entrypoint-initdb.d  # 初期SQLを配置する場合
    networks:
      - backend

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./infra/db/migrations:/migrations
    entrypoint: [ "sh", "-c", "sleep 5 && migrate -path=/migrations -database=postgres://admin:secret@db:5432/master?sslmode=disable up" ]
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
