services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./main/infra/db/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server1
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
    working_dir: /server
    command: ./server

  test:
    image: golang:1.23
    container_name: server_test_runner
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - GOFLAGS=-mod=mod
      - GOCACHE=/go-cache
    working_dir: /server
    volumes:
      - ./:/server
      - go_cache:/go-cache

volumes:
  pgdata:
  go_cache:

networks:
  backend:
    driver: bridge
